### ISSUE TITLE
Decide on an Architectural Design for the software [1.1]

### ISSUE THREAD

**Issue by Ackia** [HadrienG/metlab2#1]
As suggested during scrum meeting, Node will be used for the architectural framework. Within the current sprint, node will be implemented and dev team will familiarise themselves with the development environment.

**Comment by HadrienG** [comment]
I got started a bit, I think the basics are in place ( 🚂 🚋 🚋  work for me 🎉 ) 

So far for the general things we depend on:

- [x] [node](https://nodejs.org) 6.11.1 (LTS)
- [x] [electron](https://electron.atom.io) 1.6.10
- [x] [choo](https://choo.io) 5.6.2

Those are the big building blocks, imo the rest of the deps belong in #2
