### ISSUE TITLE
Design High-level structure of the software [1.2]

### ISSUE THREAD

**Issue by Ackia** [HadrienG/metlab2#2]
Several suggested tools were discussed during the meeting. The dev team will implement them during the current sprint and familiarise themselves with the environment.

**Comment by HadrienG** [comment]
- [x] CI with Travis
- [ ] unit testing with ? (I have a little experience with [jasmine](https://jasmine.github.io)/[karma](https://karma-runner.github.io/1.0/index.html) but open to suggestions)
- [ ] logging ( [choo-log](https://github.com/choojs/choo-log) and [electron-log](https://github.com/megahertz/electron-log) ?) 
- [ ] [electron-debug](https://github.com/sindresorhus/electron-debug)

Others (feel free to add to the list!):

- [ ] css injection ([csjs](https://github.com/rtsao/csjs) to write css in js directly)
- [ ] workflow language to link pipeline together ([watermill](https://github.com/bionode/bionode-watermill)) ?
